### ISSUE TITLE
SME Audit: Release 3 Materials - Participant Packet

### ISSUE THREAD

**Issue by cruzaprild** [usds/ditap-curriculum-update#230]
**Dependencies**
- None

**Definition of success**
- Release 3 participant packet has been reviewed per Assessment and SME audit tabs of audit rubric. [(https://docs.google.com/spreadsheets/d/15ryjqGEn9NCMztE0RjSYvNHlwWxCiU3MPUL3rCr3L3g/edit?usp=sharing)](https://docs.google.com/spreadsheets/d/1c87nkub-cBbmR-Q-gFa00NZk30Sh1_xBWqo2r50uh8U/edit?gid=1031066866#gid=1031066866)

- [ ] Participant Packet

**Other information**
- 

**Additional context**
Links to the content materials can be accessed at the content map below until In-Class sessions, Session 3. 
[Content Map](https://docs.google.com/spreadsheets/d/1kpNHBFV-v6RCWhLeIFkMvbbRR5e8t2dbtqlvnbwuevQ/edit?gid=0#gid=0)

**Comment by bevasq** [comment]
Hi @cruzaprild, I started looking at this issue and wondered if the link should be this instead of the one listed in the Definition of Success section currently? https://drive.google.com/open?id=1c87nkub-cBbmR-Q-gFa00NZk30Sh1_xBWqo2r50uh8U&usp=chrome_ntp

Please advise if I should be looking at the Release 3 and this specific document: https://docs.google.com/document/d/1JmzIZNB56sjGjAzqXnvBdsRTWIPH77VT/edit#heading=h.gjdgxs

Thank you!

**Comment by cruzaprild** [comment]
@bevasq Thanks for the question. Yes, confirming  that the document you linked is the correct one.

**Comment by bevasq** [comment]
Completed audit.
