### ISSUE TITLE
Transfer DITAP Curriculum v1 to Google

### ISSUE THREAD

**Issue by kellysmith1008** [usds/ditap-curriculum-update#56]
**Dependencies: (as applicable):** None at this time.
**Open questions:**
Do we want all content types to be in Google (ppt, word docs, pdfs, links to edX LMS, multi-media in knowledge checks)?
Yes
Why do we need to move this to Google? Is Google where we will do the audit?
We will conduct the audit in Google. Google is an easier tool for the team to use and it will be faster to get up and running with everything.
Have we already discussed this with our EX Institute partners?
Yes, we confirmed this approach (audit in Google) with Erin during the audit kickoff.
**Definition of Success:**
Transfer DITAP curriculum so that the team can review and access the material
**Additional information/notes**
Link to curriculum: https://ditap.learning-transformation.com/courses/course-v1:ICF+DITAP01+2018_T1/f74f6baf4a0d42558c13bd70b76f03e5/#:~:text=The%20following%20content%20map%20contains%20all%20of%20the

**Comment by kellysmith1008** [comment]
April will be lead on the ticket

**Comment by TahiraG** [comment]
Farooq, Tahira and April met to discuss next steps.
**Action items (due 10/22):**
Farooq to download all media materials to Google. (This is strictly a download and not organized according to the content map.)
Tahira will compare downloaded course materials with those found in content map to ensure completeness of download.
April to recreate content map in Google Sheets to track
April to request that Kelly provide feedback on organization structure (excel and files in Google).
**Future Next Steps:**
Create a task to set up meeting with USDS to confirm all pieces of the curriculum that CA should audit (owner TBD)
Request that all team members create an ICF accounts so that they have access to all curriculum materials (this could be a walkthrough at scrum?)

**Comment by TahiraG** [comment]
Created folders and sorted files through Course-level Assessments. One hurdle is files names do not match files labels in Content Map, so the matching, then sorting took some time.

**Comment by TahiraG** [comment]
Completed sorting downloaded files, creating Google docs to capture text. Ready for links to be added to Content Map.
https://drive.google.com/drive/u/2/folders/1Agm9MslIiHYe6M_nFov6ZQMFiDncehtw

**Comment by kristenjernigan** [comment]
Kristen to check for gaps between LMS content and Content Map. Tracked here: https://docs.google.com/spreadsheets/d/1kpNHBFV-v6RCWhLeIFkMvbbRR5e8t2dbtqlvnbwuevQ/edit?gid=86058716#gid=86058716 

Also, upload any missing content into LMS folder in Google Drive.

**Comment by TahiraG** [comment]
Completed a little over 75 of the 150+ document links to the content map.

**Comment by TahiraG** [comment]
Completed all links to tab 1 of content map.

**Comment by kristenjernigan** [comment]
Iteration 5.A is missing from the LMS content on EdX. Frank advised looking at CA's version of 5A and removing any CA modifications to possibly use in our audit.

**Comment by cruzaprild** [comment]
Thanks so much, Farooq! In our last refinement call, we discussed doing the LMS audit from the edx site and walked through how to set up accounts and access the materials so we are aligned there. Moving this task to done.
